project:
  type: website

execute:
  freeze: auto

website:
  title: "RLog2"
  navbar:
    right:
      - about.qmd
      - icon: mastodon
        text: Mastodon
        href: https://sigmoid.social/@kngwyu
      - icon: github
        text: Github
        href: https://github.com/kngwyu
format:
  html:
    theme: cosmo
    css: styles.css



