project:
  type: website

execute:
  freeze: auto

website:
  title: "RLog2"
  navbar:
    right:
      - about.qmd
      - icon: bluesky
        text: Bluesky
        href: https://bsky.app/profile/kngwyu.bsky.social
      - icon: github
        text: Github
        href: https://github.com/kngwyu
format:
  html:
    theme: flatly
    css: styles.css



