#!/bin/bash
# bootstrap scripts

set -eo pipefail

# Show help
function show_help() {
    echo -e "${BLUE}Usage${NC}: ./bootstrap <subcommand> [options]\n"
    echo -e "${GREEN}Subcommands${NC}:\n"
    echo "    compile Run pip-compile"
    echo "    venv    Run pip-sync"
}

function _ensure_venv() {
    if [[ ! -d .venv ]]; then
        mkdir .venv
        python -m venv .venv
        pip install pip-tools
    fi
    source .venv/bin/activate
}

function subcmd_compile() {
    _ensure_venv
    filename=$(basename "$@")
    pip-compile "$@" --output-file="requirements/${filename%.*}.txt"
}

function subcmd_register() {
    _ensure_venv
    python -m ipykernel install --user --name rlog2
}

function subcmd_sync() {
    _ensure_venv
    pip-sync "$@"
}

# Entry point: dispatch to any of sub command
readonly SUB_CMD=$1
case $SUB_CMD in
"" | "-h" | "--help")
    show_help
    ;;
*)
    shift
    subcmd_"${SUB_CMD}" "$@"
    if [ $? = 127 ]; then
        abort "$SUB_CMD is not a known subcommand. Run $CMD_NAME --help for usage."
    fi
    ;;
esac
